export const ontodataTheme = {
  token: {
    colorPrimary: '#2563eb',
    colorInfo: '#2563eb',
    colorSuccess: '#059669',
    colorWarning: '#d97706',
    colorError: '#dc2626',
    colorText: '#0f172a',
    colorTextSecondary: '#475569',
    colorTextTertiary: '#94a3b8',
    colorBorder: '#e2e8f0',
    colorBorderSecondary: '#f1f5f9',
    colorBgLayout: '#f8fafc',
    colorBgContainer: '#ffffff',
    colorBgElevated: '#ffffff',
    borderRadius: 8,
    borderRadiusLG: 12,
    borderRadiusSM: 6,
    fontSize: 14,
    fontSizeHeading1: 28,
    fontSizeHeading2: 22,
    fontSizeHeading3: 18,
    fontSizeHeading4: 15,
    fontFamily: '"Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", sans-serif',
    controlHeight: 36,
    controlHeightSM: 28,
    controlHeightLG: 42,
    boxShadowSecondary: '0 10px 15px -3px rgba(15, 23, 42, 0.08), 0 4px 6px -4px rgba(15, 23, 42, 0.04)',
  },
  components: {
    Button: {
      controlHeight: 36,
      borderRadius: 8,
      fontWeight: 500,
      primaryShadow: '0 2px 4px rgba(37, 99, 235, 0.24)',
    },
    Card: {
      borderRadiusLG: 12,
      colorBorderSecondary: '#f1f5f9',
      paddingLG: 20,
    },
    Table: {
      headerBg: '#f8fafc',
      headerColor: '#334155',
      borderColor: '#f1f5f9',
      rowHoverBg: '#f8fafc',
      padding: 12,
      paddingSM: 8,
    },
    Input: {
      controlHeight: 36,
      borderRadius: 8,
      colorBorder: '#e2e8f0',
      activeBorderColor: '#2563eb',
      hoverBorderColor: '#93c5fd',
    },
    Select: {
      controlHeight: 36,
      borderRadius: 8,
    },
    Modal: {
      borderRadiusLG: 16,
      headerBg: '#ffffff',
    },
    Tag: {
      borderRadiusSM: 4,
    },
    Progress: {
      remainingColor: '#f1f5f9',
    },
  },
}
